### PR TITLE
Fix email format for mailing lists

### PR DESCRIPTION
**Pull request by MiloCasagrande**

### CODE REVIEW

**Comment by MiloCasagrande** [comment]
@khilman, @EmbeddedAndroid , this should fix the problem with the mailing lists not getting our emails.
The kernel mailing lists (vger) refuse our emails because they are multipart and they are considered spam. The lists.linaro.org one are refusing the emails because they are too big, so I dropped the HTML part.

**Comment by khilman** [comment]
I'd like to keep the HTML for the kernel-build-reports, but drop it for all other developer lists.

I just dropped the limit from the lists.linaro.org mailman settings.  What's strange is that I'm the admin, and I never received any reports of mails not making it through.   Do you have logs/bounces of mails not getting to the linaro mailman list?

**Comment by MiloCasagrande** [comment]
Ok, we can duplicate the lines to send multipart emails to kernel-build mailing list, and default to txt only for vger.kernel.org.

Regarding the logs, this is what the bounce messages say:

Content-Policy reject msg: The message contains HTML subpart, therefore we consider it SPAM or Outlook Virus.  TEXT/PLAIN is accepted

Message size exceeds fixed limit

Plus, sometimes mail have not been delivered due to Google not able to find the recipient (broonie kernel email address).

**Comment by MiloCasagrande** [comment]
Last commit re-enable multipart emails for kernel-build-report mailing list.

**Pull request merged**
